f1 = open("myfile.txt", "r")
f2 = open("myfile2.txt", "r")
s1 = f1.read()
s2 = f2.read()
s1 = s1.split('\n')
s2 = s2.split('\n')
s1 = set(s1)
s2 = set(s2)
print(s1.difference(s2))
f1.close()
f2.close()
